---
all:
  children:
    droplet:
      hosts:
        all-in-one.teledrive.io:
          ansible_host: 157.245.76.59
          ansible_user: root
    postgresql:
      hosts:
        all-in-one.teledrive.io:
          ansible_host: 157.245.76.59
          ansible_user: root
    nginx:
      hosts:
        all-in-one.teledrive.io:
          ansible_host: 157.245.76.59
          ansible_user: root
    baseapi:
      hosts:
        all-in-one.teledrive.io:
          ansible_host: 157.245.76.59
          ansible_user: root
    teledrive:
      hosts:
        all-in-one.teledrive.io:
          ansible_host: 157.245.76.59
          ansible_user: root
