nginx_listen_ipv6: false

nginx_remove_default_vhost: true

nginx_server_tokens: "off"

nginx_client_max_body_size: "1m"

nginx_extra_http_options: |
  proxy_buffering    off;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Scheme $scheme;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   Host $http_host;

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "_"
    return: "301 https://$host$request_uri"
  - listen: "443 ssl"
    server_name: "teledrive.io"
    extra_parameters: |
      ssl_certificate /etc/nginx/ssl/teledrive.io/fullchain.pem;
      ssl_certificate_key /etc/nginx/ssl/teledrive.io/privkey.pem;

      location / {
          proxy_pass http://10.110.32.2:8080;
      }
  - listen: "443 ssl"
    server_name: "api.teledrive.io"
    extra_parameters: |
      ssl_certificate /etc/nginx/ssl/teledrive.io/fullchain.pem;
      ssl_certificate_key /etc/nginx/ssl/teledrive.io/privkey.pem;

      location / {
          proxy_pass http://10.110.32.2:8000;
      }
