# Generated by Django 4.0.5 on 2023-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tdlib", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="message",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="message",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
