# Generated by Django 4.0.5 on 2023-01-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tdlib", "0002_file_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="message",
            new_name="binary_message",
        ),
        migrations.RenameField(
            model_name="historicalfile",
            old_name="message",
            new_name="binary_message",
        ),
    ]
