# Generated by Django 4.0.5 on 2023-02-04 12:41

from django.db import migrations, models

import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("tdlib", "0002_add_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_uuid",
            field=models.CharField(db_index=True, default=utils.models.make_uuid, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="file_uuid",
            field=models.CharField(db_index=True, default=utils.models.make_uuid, max_length=255),
        ),
    ]
