# Generated by Django 4.0.5 on 2023-02-04 16:20

from django.db import migrations, models

import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0002_alter_deleted_at"),
        ("tdlib", "0003_add_file_uuid"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="file",
            index_together={("user", "file_id")},
        ),
        migrations.AlterField(
            model_name="file",
            name="file_uuid",
            field=models.CharField(default=utils.models.make_uuid, max_length=255, unique=True),
        ),
        migrations.AlterIndexTogether(
            name="file",
            index_together={("file_id", "file_uuid"), ("user", "file_id")},
        ),
    ]
