version: "3.6"
services:

  postgres:
    image: postgres:13.2
    hostname: postgres
    container_name: postgres
    networks:
      - baseapi
    environment:
      POSTGRES_DB: baseapi
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: baseapi
    ports:
      - 5432:5432

  baseapi:
    image: local/baseapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: baseapi
    container_name: baseapi
    depends_on:
      - postgres
    networks:
      - baseapi
    environment:
      DATABASE_HOST: postgres
    volumes:
      - ${PWD}:/home/app/baseapi
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; make db-migrate && make runserver"
    ports:
      - 8000:8000

networks:
  baseapi:
    name: baseapi
    driver: bridge
