name: Build API

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_DB: baseapi
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: baseapi
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: cd api && ./install_python_packages.sh
    - name: Lint
      run: cd api && make lint
    - name: Test
      run: cd api && make test
