name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: "npm"
        cache-dependency-path: web/package-lock.json

    - name: Install API Dependencies
      run: cd api && ./install_python_packages.sh
    - name: Lint API
      run: cd api && make lint

    - name: Install Web Dependencies
      run: cd web && npm ci
    - name: Lint Web
      run: cd web && make lint
    - name: Build Web
      run: cd web && NODE_ENV=production npm run build
