name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Deploy commit hash'
        required: true
      playbook_file:
        description: 'Deploy playbook file'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout hash
      run: git checkout ${{ github.event.inputs.commit_hash }}
    - name: Generate SSL Files
      run: |
        echo "$SSL_CERTIFICATE_PRIVATE_KEY" >> /tmp/privkey.pem
        echo "$SSL_CERTIFICATE_FULL_CHAIN" >> /tmp/fullchain.pem
      env:
        SSL_CERTIFICATE_PRIVATE_KEY: ${{ secrets.SSL_CERTIFICATE_PRIVATE_KEY }}
        SSL_CERTIFICATE_FULL_CHAIN: ${{ secrets.SSL_CERTIFICATE_FULL_CHAIN }}
    - name: Run Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        directory: deploy
        playbook: ${{ github.event.inputs.playbook_file }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        requirements: requirements.yaml
        options: |
          -e "postgresql_password=${{ secrets.POSTGRESQL_PASSWORD }}"
          -e "ssl_certificate_private_key_path=/tmp/privkey.pem"
          -e "ssl_certificate_full_chain_path=/tmp/fullchain.pem"
