name: Deploy API

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Deploy commit hash'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout hash
      run: git checkout ${{ github.event.inputs.commit_hash }}
    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        file: api/Dockerfile
        context: api
        tags: baseapi:${{ github.event.inputs.commit_hash }}
    - name: Docker Save
      run: docker save baseapi:${{ github.event.inputs.commit_hash }} > /tmp/baseapi-image.tar
    - name: Run Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        directory: deploy
        playbook: baseapi.yaml
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        requirements: requirements.yaml
        options: |
          -e "baseapi_image_path=/tmp/baseapi-image.tar"
          -e "baseapi_version=${{ github.event.inputs.commit_hash }}"
          -e "django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}"
          -e "postgresql_password=${{ secrets.POSTGRESQL_PASSWORD }}"
          -e "jwt_secret_key=${{ secrets.JWT_SECRET_KEY }}"
          -e "file_token_key=${{ secrets.FILE_TOKEN_KEY }}"
          -e "telepram_api_id=${{ secrets.TELEGRAM_API_ID }}"
          -e "telepram_api_hash=${{ secrets.TELEGRAM_API_HASH }}"
          -e "telepram_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}"
          -e "telepram_bot_session=${{ secrets.TELEGRAM_BOT_SESSION }}"
