name: Deploy

on:
  workflow_dispatch:
    inputs:
      playbook_file:
        type: choice
        description: Deploy playbook
        options: 
        - vm.yaml
        - api.yaml
        - web.yaml
      commit_hash:
        description: 'Deploy commit hash'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout hash
      run: git checkout ${{ github.event.inputs.commit_hash }}

    - name: API Docker Build
      if: ${{ github.event.inputs.playbook_file == 'api.yaml' }}
      uses: docker/build-push-action@v2
      with:
        file: api/Dockerfile
        context: api
        tags: api:${{ github.event.inputs.commit_hash }}

    - name: Web Docker Build
      if: ${{ github.event.inputs.playbook_file == 'web.yaml' }}
      uses: docker/build-push-action@v2
      with:
        file: web/Dockerfile
        context: web
        tags: web:${{ github.event.inputs.commit_hash }}
        build-args: |
          API_BASE_URL=https://api.teledrive.io
          GOOGLE_ANALYTICS_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}
          TELEGRAM_BOT_NAME=TeleDriveAppBot

    - name: API Docker Save
      if: ${{ github.event.inputs.playbook_file == 'api.yaml' }}
      run: docker save api:${{ github.event.inputs.commit_hash }} > /tmp/api-image.tar

    - name: Web Docker Save
      if: ${{ github.event.inputs.playbook_file == 'web.yaml' }}
      run: docker save web:${{ github.event.inputs.commit_hash }} > /tmp/web-image.tar

    - name: Run Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        directory: deploy
        playbook: ${{ github.event.inputs.playbook_file }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        requirements: requirements.yaml
        options: |
          -e "web_image_path=/tmp/web-image.tar"
          -e "web_version=${{ github.event.inputs.commit_hash }}"
          -e "api_image_path=/tmp/api-image.tar"
          -e "api_version=${{ github.event.inputs.commit_hash }}"
          -e "postgresql_host=${{ secrets.POSTGRESQL_HOST }}"
          -e "postgresql_password=${{ secrets.POSTGRESQL_PASSWORD }}"
          -e "django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}"
          -e "jwt_secret_key=${{ secrets.JWT_SECRET_KEY }}"
          -e "file_token_key=${{ secrets.FILE_TOKEN_KEY }}"
          -e "telegram_api_id=${{ secrets.TELEGRAM_API_ID }}"
          -e "telegram_api_hash=${{ secrets.TELEGRAM_API_HASH }}"
          -e "telegram_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}"
          -e "telegram_bot_session=${{ secrets.TELEGRAM_BOT_SESSION }}"
