version: "3.6"
services:
  teledrive:
    image: local/teledrive:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - REACT_APP_TELEGRAM_BOT_NAME=BotName
        - REACT_APP_API_BASE_URL=http://localhost:8000
    hostname: teledrive
    container_name: teledrive
    networks:
      - teledrive
    ports:
      - 8080:80

networks:
  teledrive:
    name: teledrive
    driver: bridge
