version: "3.6"
services:
  web:
    image: local/web:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - REACT_APP_TELEGRAM_BOT_NAME=BotName
        - REACT_APP_API_BASE_URL=http://localhost:8000
    hostname: web
    container_name: web
    networks:
      - web
    ports:
      - 8080:80

networks:
  web:
    name: web
    driver: bridge
